<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
genesis_markup(
	[
		'close'   => '</div>',
		'context' => 'site-inner',
	]
);

/**
 * Fires immediately after the site inner closing markup, before `genesis_footer` action hook.
 *
 * @since 1.0.0
 */
do_action( 'genesis_before_footer' );

/**
 * Fires to display the main footer content.
 *
 * @since 1.0.1
 */
do_action( 'genesis_footer' );

/**
 * Fires immediately after the `genesis_footer` action hook, before the site container closing markup.
 *
 * @since 1.0.0
 */
do_action( 'genesis_after_footer' );

genesis_markup(
	[
		'close'   => '</div>',
		'context' => 'site-container',
	]
);

/**
 * Fires immediately before wp_footer(), after the site container closing markup.
 *
 * @since 1.0.0
 */
do_action( 'genesis_after' );
wp_footer(); // We need this for plugins.

genesis_markup(
	[
		'close'   => '</body>',
		'context' => 'body',
	]
);

?>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<script type="text/javascript">

jQuery('#hero-slider').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    dots:false,
	autoplay:true,
    autoplayTimeout:6000,
    autoplayHoverPause:true,
    responsive:{
        0:{
            items:1
        },
        480:{
            items:1
        },
        767:{
            items:1
        },
        960:{
            items:1
        },
        1000:{
            items:1
        }
    }
});
jQuery('#client-slider').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
	dots:false,
    autoplay:true,
    autoplayTimeout:6000,
    autoplayHoverPause:true,
    responsive:{
        0:{
            items:3
        },
        480:{
            items:3
        },
        767:{
            items:3
        },
        960:{
            items:3
        },
        1000:{
            items:8
        }
    }
});
jQuery('#mob-client-slider').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
	dots:false,
    autoplay:true,
    autoplayTimeout:6000,
    autoplayHoverPause:true,
    responsive:{
        0:{
            items:3
        },
        480:{
            items:3
        },
        767:{
            items:3
        },
        960:{
            items:3
        },
        1000:{
            items:3
        }
    }
});
jQuery('#family-law').owlCarousel({
	loop:true,
    margin:10,
    nav:true,
	dots:false,
		autoplay: true,
  autoplaySpeed: 6000,
    responsive:{
        0:{
            items:1
        },
        767:{
            items:1
        },
        960:{
            items:2
        },
        1000:{
            items:3
        }
    }
});
jQuery('#emloyment-law').owlCarousel({
	loop:true,
    margin:10,
    nav:true,
	dots:false,
		autoplay: true,
  autoplaySpeed: 6000,
    responsive:{
        0:{
            items:1
        },
        767:{
            items:1
        },
        960:{
            items:2
        },
        1000:{
            items:3
        }
    }
});
jQuery('#consumer-protect').owlCarousel({
	loop:true,
    margin:10,
    nav:true,
	dots:false,
		autoplay: true,
  autoplaySpeed: 6000,
    responsive:{
        0:{
            items:1
        },
        767:{
            items:1
        },
        960:{
            items:2
        },
        1000:{
            items:3
        }
    }
});
function openCity(evt, cityName) {
  // Declare all variables
  var i, tabcontent, tablinks;

  // Get all elements with class="tabcontent" and hide them
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
  	tabcontent[i].style.display = "none";
  }

  // Get all elements with class="tablinks" and remove the class "active"
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
  	tablinks[i].className = tablinks[i].className.replace(" active", "");
  }

  // Show the current tab, and add an "active" class to the button that opened the tab
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}
</script>   
